PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX OBO: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX IAO: <http://purl.obolibrary.org/obo/IAO_>

SELECT DISTINCT ?id ?label ?definition
WHERE {
    ?disease a owl:Class .
    ?disease rdfs:label ?label .

    ?disease OBO:id ?id .
    OPTIONAL { ?disease IAO:0000115 ?definition . }
 }